{
"urls": [
{"url": "https://agit.ai/Yoursmile7/TVBox/raw/branch/master/XC.json","name": "🚀南风线路"},
{"url": "https://codeberg.org/xxpctv/ck/raw/branch/main/music/ali.py", "name": "ali线路" },
{ "url": "https://agit.ai/kvymin/TV/raw/branch/master/maoys.json", "name": "maoys"},
{"url":"https://agit.ai/kvymin/TV/raw/branch/master/Pandora.json","name":"⚡Pandora"},
{ "url": "https://神器每日推送.tk/pz.json", "name": "⚡神器接口" }, 
{"url": "https://raw.fastgit.org/FongMi/CatVodSpider/main/json/config.json","name": "蜂蜜"},
{ "url": "https://codeberg.org/xxpctv/ck/raw/branch/main/py/py_jr.py", "name": "jr" },
{"url": "https://agit.ai/nbwzlyd/xiaopingguo/raw/branch/master/xiaopingguo/xiaopingguo.json","name": "小苹果线路"},
{"url": "https://pastebin.com/raw/5NHaxyGR","name": "🚀js线路"},
{"url": "https://ghproxy.com/https://raw.githubusercontent.com/xxpctv/MusicF/main/py/py_bilimy2.py","name": "🚀m72线路"}, 
{ "url": "{ "url": "https://codeberg.org/xxpctv/ck/raw/branch/main/py/drpy%20%282%29.js", "name": "dz" },", "name": "⚡dzjs线路" },
 { "url": "http://刚刚.live/猫", "name": "⚡刚刚接口" }, 
{"url": "https://yydsys.top/duo","name": "大聪明家庭版"},
{ "url": "https://codeberg.org/xxpctv/ck/raw/branch/main/py/py_mzy.py", "name": "⚡mz线路" },
{ "url": "https://download.kstore.space/download/3313/mao/ymz","name": "ymz"}, 
{ "url": "https://dybz.store/dybz", "name": "dybz" }, 
{ "url": "https://ghproxy.com/https://raw.githubusercontent.com/xxpctv/mhx/main/plugin/tnz.php", "name": "⚡tn线路" },
{"url": "https://notabug.org/xxpctv/diy/raw/master/mao/py.py","name": "⚡央视py"},
{"url": "https://framagit.org/lzk23559/TVRule/-/raw/main/XYQTVBox.json","name": "🚀香雅情线路"},
{"url":"http://我不是.肥猫.love:63/接口禁止贩卖","name":"肥猫线路"},
{"url": "http://饭太硬.ga/tv","name": "⚡饭太硬"},
{"url": "https://pastebin.com/raw/5NHaxyGR","name": "🚀道长线路"},
{"url": "https://notabug.org/qizhen15800/My9394/raw/master/ProfessionalEdition.m3u8","name": "不良帅"},
{"url": "https://raw.iqiq.io/tuji-2015/miao/main/TVBox/tvbox.json","name": "喵影视"},
{"url": "https://ghproxy.com/https://raw.githubusercontent.com/xxpctv/MusicF/main/py/py_bilimy.py","name": "🚀m12线路"},
{"url": "https://tvbox.cainisi.cf","name": "🚀菜妮丝线路"},
{"url": "http://101.34.67.237/config/3","name": "🚀小雅线路"},
{"url": "http://dxawi.github.io/0/0.json","name": "🚀dxawi0线路"},
{"url": "https://drpyxxpctv-1.xxpctv.repl.co/config/2?ver=0","name": "🚀drpypc线路"},
{ "url": "https://agit.ai/1058263215/TVBox/raw/branch/master/JS/js0.json", "name": "道长的js0自用接口" },
{ "url": "https://dybz.store/dybz", "name": "dybz" }, 
{ "url": "https://raw.iqiq.io/zhanghong1983/TVBOXZY/main/js.json", "name": "⚡js接口" },
{ "url": "https://notabug.org/oo/gao/raw/master/js.json", "name": "⚡watson drpy1" },
{"url":"https://agit.ai/cmgyzj/tv/raw/branch/main/tt.json","name":"⚡XC1tt"},
{"url": "https://agit.ai/1058263215/TVBox/raw/branch/master/🏡电视合集1.json","name": "🏡电视合集1"},
{"url":"https://ghproxy.com/https://raw.githubusercontent.com/T00700/TVBoxSE/master/vvebo.json","name":"⚡vvebo"}
]
}
